### PR TITLE
cargo: improve and unify function regexp

### PR DESCRIPTION
**Pull request by masicn**
Far from complete but reasonable amount of function syntax added.
Partial(since matching still occurs twice) unification solves signature-name search discrepancies.

### CODE REVIEW

**Comment by psibi** [comment]
Thanks for adding tests! Is this ready to merge since you have mentioned in the PR description that it's "far from complete"? These days I use `treesit-beginning-of-defun` for a similar use case.

**Comment by masicn** [comment]
> Thanks for adding tests! Is this ready to merge since you have mentioned in the PR description that it's "far from complete"? These days I use `treesit-beginning-of-defun` for a similar use case.

The commit is fully functional and safe enough.
Regexp is incomplete but it is an improvement to previous version.

Treesiter seems like proper solution though, thanks for pointing out, I have been using old customization without it.

**Comment by psibi** [comment]
Cool, thanks! Yeah, I have completely switched to treesitter now and I find it more reliable. Details here, if you want to switch: https://github.com/emacs-rustic/rustic?tab=readme-ov-file#tree-sitter

**Comment by masicn** [comment]
> Cool, thanks! Yeah, I have completely switched to treesitter now and I find it more reliable. Details here, if you want to switch: https://github.com/emacs-rustic/rustic?tab=readme-ov-file#tree-sitter

Thank you for the merge and the instruction!

**Pull request merged**
